name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          password: ${{secrets.SSH_ENV_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            mkdir test 
            cd test 
            git clone git@github.com:jefferyyongg/my-project.git
            echo 'Deployment successful to digital ocean'
